import "Models/NameCultureInfoValue.idl";

namespace OpenNet.ViewModels.Guide
{
	[default_interface]
	runtimeclass GuideViewModel
	{
		GuideViewModel();

		UInt32 State;
		String NextOrCompleteButtonText;
		Boolean IsNextOrCompleteButtonEnabled;
		Boolean IsSetDataFolderEnabled;
		String AllCulturesWelcomeText;
		OpenNet.Models.NameCultureInfoValue SelectedCulture;

		Boolean IsTermOfServiceAgreed;
		Boolean IsPrivacyPolicyAgreed;
		Boolean IsIssueReportAgreed;
		Boolean IsOpenSourceLicenseAgreed;
		Boolean IsAgreementCopyAgreed;
	}
}
