namespace OpenNet.UI.Xaml.View.Windows
{
	[default_interface]
	runtimeclass ExceptionWindow : WinUI3Package.WindowEx
	{
		ExceptionWindow(String sentryId, String exception);

		String TraceId{ get; };
		String Exception{ get; };
		String Comment{ get; set; };

		static void Show(String sentryId, String exception);
	}
}
