namespace OpenNet.UI.Xaml.View.Windows
{
    [default_interface]
    runtimeclass RuntimeStatusWindow : WinUI3Package.WindowEx
    {
        RuntimeStatusWindow();
        Windows.Foundation.Collections.IObservableVector<Object> StatusItems{ get; };
    }
}
