namespace OpenNet.Models
{
	[default_interface]
	runtimeclass NameCultureInfoValue
	{
		NameCultureInfoValue();
	
		String Name;
		String Value;
		Boolean IsMaintainedByMSTRDI;
		Boolean IsMaintainedByCrowdin;
	}
}
