namespace OpenNet.UI.Xaml.View.Pages.SettingsPages
{
	[default_interface]
	runtimeclass MainSettingsPage : Microsoft.UI.Xaml.Controls.Page
	{
		MainSettingsPage();

		Windows.Foundation.Collections.IObservableVector<String> SettingsBarItems{ get; };
	}
}
