import "ViewModels/SettingsViewModel.idl";

namespace OpenNet.UI.Xaml.View.Pages.SettingsPages
{
    [default_interface]
    runtimeclass ThemesSettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        ThemesSettingsPage();
        OpenNet.ViewModels.SettingsViewModel ViewModel { get; };
        Int32 MaterialStyleIndex { get; };

    }
}
