import "ViewModels/MainViewModel.idl";

namespace OpenNet
{
	[default_interface]
	runtimeclass MainWindow : Microsoft.UI.Xaml.Window
	{
		MainWindow();
		Microsoft.UI.Xaml.Visibility IsDebug { get; };
		OpenNet.ViewModels.MainViewModel ViewModel { get; };
		void Navigate(String tag);
	}
}