import "ViewModels/MainViewModel.idl";

namespace OpenNet
{
	[default_interface]
	runtimeclass MainWindow : WinUI3Package.WindowEx
	{
		MainWindow();
		Microsoft.UI.Xaml.Visibility IsDebug { get; };
		OpenNet.ViewModels.MainViewModel ViewModel { get; };
		void Navigate(Windows.UI.Xaml.Interop.TypeName pageType);
	}
}
