#pragma once
#include "XamlWorkaround.h"
#include "UI\Xaml\Control\InfoBarHelper.h"
#include "UI\Xaml\Control\InfoBarTemplateSelector.h"
// The .cpp files generated by the XamlCompiler unconditionally include the pch.h, so this file must exist, but it does not need to have any content.
