#pragma once
// The purpose of this file is to convert includes from the files generated by XamlCompiler into imports.
// For the .g.cpp files generated by the XamlCompiler, this file is added to the beginning of the include list via the `/FI`.
// For `.xaml.cpp` or `.xaml.h` files, it should be included before `xaml.h` or `xaml.g.h` but after other header files.

// Mark that we want C++/WinRT headers to use module imports instead of #include
#ifndef WINRT_IMPORT_MODULE
#define WINRT_IMPORT_MODULE
#endif

// Include Windows SDK basics BEFORE setting any blocking macros.
// This provides HANDLE, DWORD, HWND, IUnknown, GUID, BOOL, PCWSTR, STDAPI, etc.
#include <windows.h>

// The .cpp files generated by the XamlCompiler still include these C++/WinRT-related header files,
// so they also need to be blocked out. These are NOT Windows SDK headers - they are COM/RPC headers
// that conflict with WinRT module imports.
#ifndef __unknwn_h__
#define __unknwn_h__
#endif
#ifndef __RPC_H__
#define __RPC_H__
#endif
#ifndef __RPCNDR_H__
#define __RPCNDR_H__
#endif
#ifndef _INC_WINAPIFAMILY
#define _INC_WINAPIFAMILY
#endif
#ifndef _INC_WINPACKAGEFAMILY
#define _INC_WINPACKAGEFAMILY
#endif
#ifndef _OLE2_H_
#define _OLE2_H_
#endif
#ifndef _INC_SDKDDKVER
#define _INC_SDKDDKVER
#endif

// Block C++ standard library headers that are replaced by import std;.
// The XamlCompiler-generated .g.cpp files still try to include these.
#ifndef _FUNCTIONAL_
#define _FUNCTIONAL_
#endif
#ifndef _VECTOR_
#define _VECTOR_
#endif
#ifndef _MAP_
#define _MAP_
#endif
#ifndef _MUTEX_
#define _MUTEX_
#endif
#ifndef _REGEX_
#define _REGEX_
#endif
#ifndef _MEMORY_
#define _MEMORY_
#endif
#ifndef _STRING_
#define _STRING_
#endif

// Import modules to satisfy the requirements of the .cpp files generated by the XamlCompiler.
import std;
import winrt.Windows.Foundation;
import winrt.Microsoft.UI.Xaml.Markup;
import winrt.Microsoft.UI.Xaml.Interop;
import winrt.Windows.UI.Xaml.Interop;
import winrt.Microsoft.UI.Xaml;
import winrt.Microsoft.UI.Xaml.XamlTypeInfo;
import winrt.WinUI3Package;
import winrt.XamlToolkit.WinUI;
import winrt.XamlToolkit.WinUI.Controls;
