namespace OpenNet.UI.Xaml.Behaviors
{
    [default_interface]
    runtimeclass StickyHeaderBehavior : Microsoft.UI.Xaml.Controls.Control
    {
        StickyHeaderBehavior();
        void Attach(Microsoft.UI.Xaml.DependencyObject associatedObject);
        void Detach();
        Microsoft.UI.Xaml.DependencyObject AssociatedObject{ get; };
        void Show();
    }
}
