import "ViewModels/NetworkSettingsViewModel.idl";

namespace OpenNet.UI.Xaml.View.Pages
{
    [default_interface]
    runtimeclass NetworkSettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        NetworkSettingsPage();
        OpenNet.ViewModels.NetworkSettingsViewModel ViewModel { get; };

        // Tracker properties
        Windows.Foundation.Collections.IObservableVector<String> TrackerList{ get; };
        Windows.Foundation.Collections.IObservableVector<String> SubscriptionList{ get; };
    }
}