import "ViewModels/DataTableSortViewModel.idl";
import "ViewModels/DisplayItems.idl";

namespace OpenNet.UI.Xaml.View.Pages
{
    [default_interface]
    runtimeclass TaskFilesPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        TaskFilesPage();
        OpenNet.ViewModels.DataTableSortViewModel SortState { get; };
		Windows.Foundation.Collections.IObservableVector<OpenNet.ViewModels.FileDisplayItem> FileTree{ get; };
    }
}
