import "ViewModels/TasksViewModel.idl";

namespace OpenNet.UI.Xaml.View.Pages
{
    [default_interface]
    runtimeclass TasksPage : Microsoft.UI.Xaml.Controls.Page
    {
        TasksPage();

        // Strongly-typed view model for x:Bind
        OpenNet.ViewModels.TasksViewModel ViewModel { get; };
    }
}
