namespace OpenNet.UI.Xaml.Behavior
{
    [default_interface]
    runtimeclass InfoBarDelayCloseBehavior : Microsoft.UI.Xaml.DependencyObject, XamlToolkit.WinUI.Interactivity.IBehavior
    {
        InfoBarDelayCloseBehavior();
        static Microsoft.UI.Xaml.DependencyProperty MilliSecondsDelayProperty{ get; };
        UInt32 MilliSecondsDelay;
    }
}
