namespace OpenNet.UI.Shell
{
	[default_interface]
	runtimeclass NotifyIconXamlHostWindow : WinUI3Package.WindowEx
	{
		NotifyIconXamlHostWindow();
		static Guid IconGuid{ get; };
		void ShowMainWindow();
		void Show();
		void Remove();
	}
}
