namespace OpenNet.UI.Shell
{
	[default_interface]
	runtimeclass NotifyIconContextMenu : Microsoft.UI.Xaml.Controls.Flyout
	{
		NotifyIconContextMenu();

		String Title{ get; };
		void ExitApplication();
	}
}
