name: Canary

on:
  push:
    branches-ignore:
      - l10n_develop
      - master
      - release
      - dependabot/**
    paths-ignore:
      - '.gitattributes'
      - '.github/**'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - '**.yml'

env:
  USERNAME: hoshiizumiya
  FEED_URL: https://nuget.pkg.github.com/hoshiizumiya/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/hoshiizumiya/index.json,readwrite"
  
jobs:

  build:
    runs-on: windows-2025-vs2026

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: microsoft/setup-msbuild@v2
      - uses: nuget/setup-nuget@v2

      - name: Set up vcpkg
        working-directory: ${{env.VCPKG_INSTALLATION_ROOT}}
        run: vcpkg integrate install
      
      - name: Add NuGet sources
        shell: pwsh
        run: |
          $nuget = & "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe" fetch nuget
      
          & $nuget sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.GITHUB_TOKEN }}"
      
          & $nuget setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"

      - name: Restore NuGet
        run: nuget restore OpenNet.slnx
        shell: pwsh

      - name: Restore Certificate
        run: |
          $bytes = [Convert]::FromBase64String("${{ secrets.PFX_CERT_BASE64 }}")
          $certPath = "$env:GITHUB_WORKSPACE\cert.pfx"
          [IO.File]::WriteAllBytes("cert.pfx", $bytes)
          Write-Host "Certificate restored to:"
          Write-Host $certPath
        working-directory: ${{ github.workspace }}
        shell: pwsh

      - name: Import Certificate
        id: import_cert
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          $certPath = "$env:GITHUB_WORKSPACE\cert.pfx"
     
          $password = ConvertTo-SecureString `
            "${{ secrets.PFX_PASSWORD }}" `
            -AsPlainText `
            -Force
     
          $cert = Import-PfxCertificate `
            -FilePath $certPath `
            -CertStoreLocation "Cert:\CurrentUser\My" `
            -Password $password
     
          Write-Host "Certificate imported."
     
          $thumb = $cert.Thumbprint
          Write-Host "Thumbprint: $thumb"
     
          echo "thumbprint=$thumb" >> $env:GITHUB_OUTPUT
        
      - name: Show Installed Certificates
        shell: pwsh
        run: |
          Get-ChildItem Cert:\CurrentUser\My |
            Select Subject, Thumbprint
        
      - name: Build MSIX
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          msbuild OpenNet\OpenNet.vcxproj `
            /p:Configuration=${{ matrix.configuration }} `
            /p:Platform=${{ matrix.platform }} `
            /p:GenerateAppxPackageOnBuild=true `
            /p:UapAppxPackageBuildMode=SideloadOnly `
            /p:AppxPackageDir=AppPackages\ `
            /p:AppxPackageSigningEnabled=true `
            /p:PackageCertificateThumbprint="${{ steps.import_cert.outputs.thumbprint }}" `
            /m

      - name: Generate Date
        run: |
          $date = Get-Date -Format yyyyMMdd
          Add-Content -Path $Env:GITHUB_ENV -Value "DATE=$date"
        shell: pwsh

      - name: Show build output
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Path OpenNet | Where-Object {$_.Name -like "*.msix"}

      - name: 7z Package
        run: |
          if (-not (Get-Command 7z -ErrorAction SilentlyContinue)) {
            choco install 7zip -y
          }

          7z a -t7z -mx=9 `
            "OpenNet.Canary_${{ env.DATE }}_${{ matrix.platform }}.7z" `
            "AppPackages\\"
        shell: pwsh
        
      - name: Upload Canary Artifact
        uses: actions/upload-artifact@v6
        with:
          name: OpenNet.Canary_${{ env.DATE }}_${{ matrix.platform }}
          path: |
            OpenNet.Canary_${{ env.DATE }}_${{ matrix.platform }}.7z